name: Build Status

on:
  push:
    branches:
      - main
      - master
    tags:
      - v*
    paths-ignore:
      - docs/
      - LICENSE
      - README.md
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
        cache-dependency-path: yarn.lock

    - name: Install yarn
      run: npm install -g yarn

    - name: Install dependencies
      run: yarn

    - name: Build 
      run: |
        yarn build
        yarn webpack

    - name: Test
      run: yarn test
